name: insightflow_ai
description: Autonomous Content-to-Action Agent
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  provider: ^6.1.0
  confetti: ^0.7.0

flutter:
  uses-material-design: true
